#!/bin/bash
# Quick reference for Home Assistant in dev environment

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║        Home Assistant Development Environment                ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "🏠 Installation Type: Home Assistant CORE (Python)"
echo "📦 HACS: Installed in /config/custom_components/hacs"
echo "🎬 Stremio: Available as custom integration"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  IMPORTANT: About Add-ons and HACS"
echo ""
echo "❌ No 'Add-ons' menu - This is normal!"
echo "   → Add-ons only exist in Home Assistant OS/Supervised"
echo "   → You're running Core (development mode)"
echo ""
echo "✅ HACS Setup:"
echo "   1. Start Home Assistant: ./scripts/start_homeassistant.sh"
echo "   2. Open: http://localhost:8123"
echo "   3. Go to: Settings → Devices & Services → Integrations"
echo "   4. Click: + Add Integration"
echo "   5. Search: HACS"
echo "   6. Complete setup wizard"
echo "   7. HACS will appear in the left sidebar"
echo ""
echo "✅ Stremio Setup:"
echo "   1. In same Integrations page"
echo "   2. Click: + Add Integration"
echo "   3. Search: Stremio"
echo "   4. Enter your Stremio credentials"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 Full Documentation:"
echo "   → docs/dev-environment-hacs.md"
echo "   → docs/setup.md"
echo ""
echo "🚀 Quick Start:"
echo "   → Start HA: ./scripts/start_homeassistant.sh"
echo "   → Run tests: pytest tests/"
echo "   → Check logs: tail -f config/home-assistant.log"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
